SOF1 = 0xA5
SOF2 = 0x5A
VER = 0x01

TYPE_REQ = 0x01
TYPE_RESP = 0x02
TYPE_ACK = 0x03
TYPE_NACK = 0x04
TYPE_EVENT = 0x05
TYPE_DATA = 0x06
TYPE_WINDOW_ACK = 0x07

MAX_PAYLOAD = 128

MCU_INFO_CMD_PING = 0x01
MCU_INFO_CMD_GET_VERSION = 0x02
MCU_INFO_CMD_GET_STATUS = 0x03
MCU_INFO_CMD_GET_RESET_INFO = 0x04
MCU_INFO_CMD_GET_TIME_INFO = 0x05
MCU_INFO_CMD_GET_FAULT_INFO = 0x06
MCU_INFO_CMD_GET_UART_STATS = 0x07
MCU_INFO_CMD_GET_APP_STATS = 0x08
MCU_INFO_CMD_GET_EVENT_STATS = 0x09
MCU_INFO_CMD_GET_COMMAND_STATS = 0x0D

CMD_UNKNOWN_TEST = 0x7E

MCU_INFO_EVENT_BOOT = 0x81
MCU_INFO_EVENT_HEARTBEAT = 0x82
MCU_INFO_EVENT_RUNTIME_STATUS = 0x83
MCU_INFO_EVENT_UART_WARNING = 0x84
MCU_INFO_EVENT_APP_MESSAGE = 0x85
MCU_INFO_EVENT_FAULT = 0x86

PROTO_ERROR_OK = 0x00
PROTO_ERROR_UNKNOWN_CMD = 0x01
PROTO_ERROR_INVALID_LEN = 0x02
PROTO_ERROR_CRC_ERROR = 0x03
PROTO_ERROR_INVALID_STATE = 0x04
PROTO_ERROR_BUSY = 0x05
PROTO_ERROR_INTERNAL_ERROR = 0x06
PROTO_ERROR_AUTH_REQUIRED = 0x07
PROTO_ERROR_TIMEOUT = 0x08
PROTO_ERROR_INVALID_PARAM = 0x09
PROTO_ERROR_WINDOW_FULL = 0x0A
PROTO_ERROR_DUPLICATE_FRAME = 0x0B
PROTO_ERROR_UNSUPPORTED_VERSION = 0x0C

DIAG_CMD_GET_HEALTH = 0x20
DIAG_CMD_GET_ERROR_COUNTERS = 0x21
DIAG_CMD_GET_BUFFER_STATS = 0x22
DIAG_CMD_GET_TIMING_STATS = 0x23
DIAG_CMD_GET_LAST_RECORDS = 0x24
DIAG_CMD_GET_PIPELINE_STATS = 0x25
DIAG_CMD_CLEAR_COUNTERS = 0x26

# Stage 4 IMU commands
IMU_CMD_GET_RAW = 0x30
IMU_CMD_GET_FILTERED = 0x31
IMU_CMD_GET_STATUS = 0x32
IMU_CMD_GET_ALGO_STATS = 0x36
IMU_CMD_SET_SAMPLE_RATE = 0x37
IMU_CMD_START_STREAM = 0x38
IMU_CMD_STOP_STREAM = 0x39
IMU_CMD_START = 0x3A
IMU_CMD_STOP = 0x3B
IMU_CMD_GET_ATTITUDE = 0x3C
IMU_CMD_CLEAR_STATS = 0x3D

# Stage 4 IMU events and app id
IMU_APP_ID = 5
IMU_EVENT_STARTED = 0x90
IMU_EVENT_STOPPED = 0x91
IMU_EVENT_ERROR = 0x95
IMU_EVENT_ATTITUDE = 0x97
IMU_EVENT_RAW_SAMPLE = 0x98

# Stage 6 stream / block data commands.
# These must match MCU StreamManager / BlockManager.
STREAM_MANAGER_DATA_CMD = 0x70
BLOCK_MANAGER_DATA_CMD = 0x71

# Stream channels. These must match stream_manager.h.
STREAM_CHANNEL_IMU = 0x01
STREAM_CHANNEL_TRACE = 0x02
STREAM_CHANNEL_LOG = 0x03
STREAM_CHANNEL_USER = 0x04

STREAM_CHANNEL_NAME_MAP = {
    STREAM_CHANNEL_IMU: "IMU",
    STREAM_CHANNEL_TRACE: "TRACE",
    STREAM_CHANNEL_LOG: "LOG",
    STREAM_CHANNEL_USER: "USER",
}

# Stream DATA flags. These must match stream_manager.h.
STREAM_FLAG_DROP_ALLOWED = 0x01
STREAM_FLAG_IMPORTANT = 0x02

# Block transfer operations. These must match block_manager.h.
BLOCK_OP_BEGIN = 0x01
BLOCK_OP_CHUNK = 0x02
BLOCK_OP_END = 0x03
BLOCK_OP_ABORT = 0x04
BLOCK_OP_ACK = 0x05
BLOCK_OP_NACK = 0x06

BLOCK_OP_NAME_MAP = {
    BLOCK_OP_BEGIN: "BEGIN",
    BLOCK_OP_CHUNK: "CHUNK",
    BLOCK_OP_END: "END",
    BLOCK_OP_ABORT: "ABORT",
    BLOCK_OP_ACK: "ACK",
    BLOCK_OP_NACK: "NACK",
}

# Block DATA flags. These must match block_manager.h.
BLOCK_FLAG_NEED_ACK = 0x01
BLOCK_FLAG_MORE = 0x02
BLOCK_FLAG_RETRY = 0x04

FRAME_TYPE_NAME_MAP = {
    TYPE_REQ: "REQ",
    TYPE_RESP: "RESP",
    TYPE_ACK: "ACK",
    TYPE_NACK: "NACK",
    TYPE_EVENT: "EVENT",
    TYPE_DATA: "DATA",
    TYPE_WINDOW_ACK: "WINDOW_ACK",
}


EVENT_NAME_MAP = {
    MCU_INFO_EVENT_BOOT: "BOOT",
    MCU_INFO_EVENT_HEARTBEAT: "HEARTBEAT",
    MCU_INFO_EVENT_RUNTIME_STATUS: "RUNTIME_STATUS",
    MCU_INFO_EVENT_UART_WARNING: "UART_WARNING",
    MCU_INFO_EVENT_APP_MESSAGE: "APP_MESSAGE",
    MCU_INFO_EVENT_FAULT: "FAULT",
    IMU_EVENT_STARTED: "IMU_STARTED",
    IMU_EVENT_STOPPED: "IMU_STOPPED",
    IMU_EVENT_ERROR: "IMU_ERROR",
    IMU_EVENT_ATTITUDE: "IMU_ATTITUDE",
    IMU_EVENT_RAW_SAMPLE: "IMU_RAW_SAMPLE",
}


APP_ID_MAP = {
    0: "SYSTEM",
    1: "UART",
    2: "FAULT",
    3: "USER",
    4: "RESET",
    IMU_APP_ID: "IMU",
}


ERROR_NAME_MAP = {
    PROTO_ERROR_OK: "OK",
    PROTO_ERROR_UNKNOWN_CMD: "UNKNOWN_CMD",
    PROTO_ERROR_INVALID_LEN: "INVALID_LEN",
    PROTO_ERROR_CRC_ERROR: "CRC_ERROR",
    PROTO_ERROR_INVALID_STATE: "INVALID_STATE",
    PROTO_ERROR_BUSY: "BUSY",
    PROTO_ERROR_INTERNAL_ERROR: "INTERNAL_ERROR",
    PROTO_ERROR_AUTH_REQUIRED: "AUTH_REQUIRED",
    PROTO_ERROR_TIMEOUT: "TIMEOUT",
    PROTO_ERROR_INVALID_PARAM: "INVALID_PARAM",
    PROTO_ERROR_WINDOW_FULL: "WINDOW_FULL",
    PROTO_ERROR_DUPLICATE_FRAME: "DUPLICATE_FRAME",
    PROTO_ERROR_UNSUPPORTED_VERSION: "UNSUPPORTED_VERSION",
}


def event_name(event_id: int) -> str:
    return EVENT_NAME_MAP.get(event_id, f"EVENT_0x{event_id:02X}")


def app_name(app_id: int) -> str:
    return APP_ID_MAP.get(app_id, f"APP_{app_id}")


def error_name(error_code: int) -> str:
    return ERROR_NAME_MAP.get(error_code, f"ERROR_0x{error_code:02X}")


def stream_channel_name(channel_id: int) -> str:
    return STREAM_CHANNEL_NAME_MAP.get(channel_id, f"STREAM_CH_0x{channel_id:02X}")


def block_op_name(op: int) -> str:
    return BLOCK_OP_NAME_MAP.get(op, f"BLOCK_OP_0x{op:02X}")

# Stage 7 StorageApp commands. Must match storage_app.h.
STORAGE_CMD_GET_INFO = 0xA0
STORAGE_CMD_GET_PARTITION_COUNT = 0xA1
STORAGE_CMD_GET_PARTITION_INFO = 0xA2
STORAGE_CMD_ERASE_PARTITION = 0xA3
STORAGE_CMD_WRITE_PARTITION_BEGIN = 0xA4
STORAGE_CMD_READ_PARTITION_BEGIN = 0xA5
STORAGE_CMD_GET_STATS = 0xA6
STORAGE_CMD_ABORT_TRANSFER = 0xA7

STORAGE_STATUS_OK = 0x00
STORAGE_STATUS_ERROR = 0x01
STORAGE_STATUS_INVALID_PARAM = 0x02
STORAGE_STATUS_DENIED = 0x03
STORAGE_STATUS_BUSY = 0x04
STORAGE_STATUS_STORAGE_ERROR = 0x05
STORAGE_STATUS_NOT_FOUND = 0x06

STORAGE_STATUS_NAME_MAP = {
    STORAGE_STATUS_OK: "OK",
    STORAGE_STATUS_ERROR: "ERROR",
    STORAGE_STATUS_INVALID_PARAM: "INVALID_PARAM",
    STORAGE_STATUS_DENIED: "DENIED",
    STORAGE_STATUS_BUSY: "BUSY",
    STORAGE_STATUS_STORAGE_ERROR: "STORAGE_ERROR",
    STORAGE_STATUS_NOT_FOUND: "NOT_FOUND",
}

STORAGE_CMD_NAME_MAP = {
    STORAGE_CMD_GET_INFO: "STORAGE_GET_INFO",
    STORAGE_CMD_GET_PARTITION_COUNT: "STORAGE_GET_PARTITION_COUNT",
    STORAGE_CMD_GET_PARTITION_INFO: "STORAGE_GET_PARTITION_INFO",
    STORAGE_CMD_ERASE_PARTITION: "STORAGE_ERASE_PARTITION",
    STORAGE_CMD_WRITE_PARTITION_BEGIN: "STORAGE_WRITE_PARTITION_BEGIN",
    STORAGE_CMD_READ_PARTITION_BEGIN: "STORAGE_READ_PARTITION_BEGIN",
    STORAGE_CMD_GET_STATS: "STORAGE_GET_STATS",
    STORAGE_CMD_ABORT_TRANSFER: "STORAGE_ABORT_TRANSFER",
}


def storage_status_name(status: int) -> str:
    return STORAGE_STATUS_NAME_MAP.get(status, f"STORAGE_STATUS_0x{status:02X}")


def storage_cmd_name(cmd: int) -> str:
    return STORAGE_CMD_NAME_MAP.get(cmd, f"STORAGE_CMD_0x{cmd:02X}")
