SOF1 = 0xA5
SOF2 = 0x5A
VER = 0x01

TYPE_REQ = 0x01
TYPE_RESP = 0x02
TYPE_ACK = 0x03
TYPE_NACK = 0x04
TYPE_EVENT = 0x05
TYPE_DATA = 0x06
TYPE_WINDOW_ACK = 0x07

MAX_PAYLOAD = 128

MCU_INFO_CMD_PING = 0x01
MCU_INFO_CMD_GET_VERSION = 0x02
MCU_INFO_CMD_GET_STATUS = 0x03
MCU_INFO_CMD_GET_RESET_INFO = 0x04
MCU_INFO_CMD_GET_TIME_INFO = 0x05
MCU_INFO_CMD_GET_FAULT_INFO = 0x06
MCU_INFO_CMD_GET_UART_STATS = 0x07
MCU_INFO_CMD_GET_APP_STATS = 0x08

CMD_UNKNOWN_TEST = 0x7E

MCU_INFO_EVENT_BOOT = 0x81
MCU_INFO_EVENT_HEARTBEAT = 0x82
MCU_INFO_EVENT_RUNTIME_STATUS = 0x83
MCU_INFO_EVENT_UART_WARNING = 0x84
MCU_INFO_EVENT_APP_MESSAGE = 0x85
MCU_INFO_EVENT_FAULT = 0x86

PROTO_ERROR_OK = 0x00
PROTO_ERROR_UNKNOWN_CMD = 0x01
PROTO_ERROR_INVALID_LEN = 0x02
PROTO_ERROR_CRC_ERROR = 0x03
PROTO_ERROR_INVALID_STATE = 0x04
PROTO_ERROR_BUSY = 0x05
PROTO_ERROR_INTERNAL_ERROR = 0x06
PROTO_ERROR_AUTH_REQUIRED = 0x07
PROTO_ERROR_TIMEOUT = 0x08
PROTO_ERROR_INVALID_PARAM = 0x09
PROTO_ERROR_WINDOW_FULL = 0x0A
PROTO_ERROR_DUPLICATE_FRAME = 0x0B
PROTO_ERROR_UNSUPPORTED_VERSION = 0x0C


FRAME_TYPE_NAME_MAP = {
    TYPE_REQ: "REQ",
    TYPE_RESP: "RESP",
    TYPE_ACK: "ACK",
    TYPE_NACK: "NACK",
    TYPE_EVENT: "EVENT",
    TYPE_DATA: "DATA",
    TYPE_WINDOW_ACK: "WINDOW_ACK",
}


EVENT_NAME_MAP = {
    MCU_INFO_EVENT_BOOT: "BOOT",
    MCU_INFO_EVENT_HEARTBEAT: "HEARTBEAT",
    MCU_INFO_EVENT_RUNTIME_STATUS: "RUNTIME_STATUS",
    MCU_INFO_EVENT_UART_WARNING: "UART_WARNING",
    MCU_INFO_EVENT_APP_MESSAGE: "APP_MESSAGE",
    MCU_INFO_EVENT_FAULT: "FAULT",
}


APP_ID_MAP = {
    0: "SYSTEM",
    1: "UART",
    2: "FAULT",
    3: "USER",
}


ERROR_NAME_MAP = {
    PROTO_ERROR_OK: "OK",
    PROTO_ERROR_UNKNOWN_CMD: "UNKNOWN_CMD",
    PROTO_ERROR_INVALID_LEN: "INVALID_LEN",
    PROTO_ERROR_CRC_ERROR: "CRC_ERROR",
    PROTO_ERROR_INVALID_STATE: "INVALID_STATE",
    PROTO_ERROR_BUSY: "BUSY",
    PROTO_ERROR_INTERNAL_ERROR: "INTERNAL_ERROR",
    PROTO_ERROR_AUTH_REQUIRED: "AUTH_REQUIRED",
    PROTO_ERROR_TIMEOUT: "TIMEOUT",
    PROTO_ERROR_INVALID_PARAM: "INVALID_PARAM",
    PROTO_ERROR_WINDOW_FULL: "WINDOW_FULL",
    PROTO_ERROR_DUPLICATE_FRAME: "DUPLICATE_FRAME",
    PROTO_ERROR_UNSUPPORTED_VERSION: "UNSUPPORTED_VERSION",
}


def event_name(event_id: int) -> str:
    return EVENT_NAME_MAP.get(event_id, f"EVENT_0x{event_id:02X}")


def app_name(app_id: int) -> str:
    return APP_ID_MAP.get(app_id, f"APP_{app_id}")


def error_name(error_code: int) -> str:
    return ERROR_NAME_MAP.get(error_code, f"ERROR_0x{error_code:02X}")